replicaCount: 1

image:
  repository: ${{ secrets.DOCKER_USERNAME }}/myapp
  pullPolicy: IfNotPresent
  tag: "1.0.1"  # Replace this with the actual image tag

service:
  type: ClusterIP
  port: 8080

resources: {}
