replicaCount: 1

image:
  repository: ${{ secrets.DOCKER_USERNAME }}//myapp
  pullPolicy: IfNotPresent
  tag: "1.0.1"  # Replace with your app version

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

serviceAccount:
  create: true
  # Add other serviceAccount related configurations if necessary