name: Java CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution here

    - name: Auto-Increment Patch Version
      run: ./scripts/auto_increment_version.sh

    - name: Compile and Package
      run: mvn clean package

    - name: Build Docker Image
      run: docker build -t myapp:${{ steps.version.outputs.NEW_VERSION }} .

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image to Docker Hub
      run: docker push username/myapp:${{ steps.version.outputs.NEW_VERSION }}
