name: Java CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution here

    - name: Auto-Increment Patch Version
      id: auto_increment_version  # Adding an ID here
      run: ../scripts/auto_increment_version.sh
      working-directory: ./myapp

    - name: Compile and Package
      run: mvn clean package
      working-directory: ./myapp

    - name: List contents of the myapp directory
      run: ls -la
      working-directory: ./myapp

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.auto_increment_version.outputs.NEW_VERSION }} .
      working-directory: ./myapp      

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.auto_increment_version.outputs.NEW_VERSION }}
